#!name= 小红书 𝕏
#!desc= 小红书去除视频
#!author=🌲
#!icon= https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/RedPaper.png


[Rewrite]
^https:\/\/so\.xiaohongshu\.com\/api\/sns\/v\d+\/search\/notes response-body-json-jq '.data.items |= map(select(.note?.type == "normal"))'
^https:\/\/rec\.xiaohongshu\.com\/api\/sns\/v\d+\/homefeed response-body-json-jq '.data |= map(select(.type == "normal"))'

[MitM]
hostname = *.xiaohongshu.com, -edith.xiaohongshu.com, -t2.xiaohongshu.com, -apm-native.xiaohongshu.com, -as.xiaohongshu.com, -spider-tracker.xiaohongshu.com, -lng.xiaohongshu.com, -fe.xiaohongshu.com, -crash.xiaohongshu.com, -fe-resource-app.xiaohongshu.com
