[rewrite_local]
# --- 学籍测试：列表显示本科，详情显示本科 / 在籍 ---
^https?:\/\/my\.chsi\.com\.cn\/archive\/wap\/gdjy\/(?:search|xj\/detail)\.action(?:\?.*)?$ url script-response-body https://raw.githubusercontent.com/oooasis/re/refs/heads/main/enrollment-rewrite.js

[mitm]
hostname = my.chsi.com.cn
