host, weather-analytics-events.apple.com, reject
host-suffix, tthr.apple.com, reject
host, tether.edge.apple, reject
host, weatherkit.pages.dev, direct

^https?:\/\/weatherkit\.apple\.com\/api\/v1\/availability\/ url script-echo-response https://raw.githubusercontent.com/oooasis/re/refs/heads/main/Weather.qx.js
^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/ url script-echo-response https://raw.githubusercontent.com/oooasis/re/refs/heads/main/Weather.qx.js
^https?:\/\/weatherkit\.apple\.com\/api\/v1\/weatherAlerts\?([^#]*&ids=[^&#]*-[0-9]{9}(?:&[^#]*)?)$ url script-echo-response https://raw.githubusercontent.com/oooasis/re/refs/heads/main/Weather.qx.js
^https?:\/\/weatherkit\.apple\.com\/api\/v1\/weatherAlerts\?([^#]*&ids=-?[0-9]+(?:\.[0-9]+)?,-?[0-9]+(?:\.[0-9]+)?(?:&[^#]*)?)$ url script-echo-response https://raw.githubusercontent.com/oooasis/re/refs/heads/main/Weather.qx.js

hostname = weatherkit.apple.com
