hostname = rec.xiaohongshu.com, edith.xiaohongshu.com, gslb.xiaohongshu.com, mediacloud.xiaohongshu.com, www.xiaohongshu.com

^https?:\/\/[a-z]+\.xiaohongshu\.com\/api/sns/v\d/(homefeed|localfeed) url jsonjq-response-body '.data |= map(select(.type == "normal"))'
