#!name=小红书
#!desc=小红书去除视频 QX 优化版
#!author=🌲

^https:\/\/rec\.xiaohongshu\.com\/api\/sns\/v\d+\/(homefeed|localfeed)(\?|$) url jsonjq-response-body '.data |= map(select(.type == "normal"))'
^https:\/\/(so|search)\.xiaohongshu\.com\/api\/sns\/v\d+\/search\/notes(\?|$) url jsonjq-response-body '.data.items |= map(select(.note?.type == "normal"))'

hostname = rec.xiaohongshu.com, so.xiaohongshu.com, search.xiaohongshu.com
